preset: none

enabled:
  - blank_line_after_namespace
  - blank_line_before_return
  - cast_spaces
  - combine_consecutive_unsets
  - concat_with_spaces
  - elseif
  - encoding
  - full_opening_tag
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - linebreak_after_opening_tag
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - method_visibility_required
  - native_function_casing
  - no_closing_tag
  - no_extra_consecutive_blank_lines
  - no_php4_constructor
  - no_short_echo_tag
  - no_spaces_after_function_name
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_useless_else
  - no_whitespace_before_comma_in_array
  - not_operator_with_space
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_scalar
  - property_visibility_required
  - short_scalar_cast
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_quote
  - standardize_not_equals
  - strict_comparison
  - switch_case_semicolon_to_colon
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - unix_line_endings
  - whitespace_after_comma_in_array

finder:
  exclude:
    - ".dev"
    - "lib"
    - "tests"
  name:
    - "*.php"
